- name: Mongodb Setup
  hosts: all
  become: yes
  tasks:
    - name: copy mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB
      ansible.builtin.yum:
        name: mongodb-org
        state: installed

    - name: Change Listenaddress
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start MongoDB Service
      ansible.builtin.systemd:
        name: mongod
        state: restarted
        enabled: yes






#-----------------------------------------------------------------------------------------------------
#log=/tmp/roboshop.log
#echo -e "\e[36m >>>>>>>>>>>>mongo repo files<<<<<<<<<<<<<<<< \e[0m" | tee -a /tmp/roboshop.log
#cp mongo.repo /etc/yum.repos.d/mongo.repo &>>$log
#-----------------------------------------------------------------------------------------------------

#-----------------------------------------------------------------------------------------------------
#echo -e "\e[36m >>>>>>>>>>>>Installing mongoDB<<<<<<<<<<<<<<<< \e[0m" | tee -a /tmp/roboshop.log
#yum install mongodb-org -y &>>$log
#-----------------------------------------------------------------------------------------------------


#-----------------------------------------------------------------------------------------------------
#echo -e "\e[36m >>>>>>>>>>>>Changing liste address<<<<<<<<<<<<<<<< \e[0m" | tee -a /tmp/roboshop.log
#sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
#Update listen address
#-----------------------------------------------------------------------------------------------------

#echo -e "\e[36m >>>>>>>>>>>>Enabling and restarting mongodb<<<<<<<<<<<<<<<< \e[0m" | tee -a /tmp/roboshop.log
#systemctl enable mongod
#systemctl start mongod
#systemctl restart mongod &>>$log