#cp mysql.repo /etc/yum.repos.d/mysql.repo &>>${log}
#yum module disable mysql -y  &>>${log}
#yum install mysql-community-server -y  &>>${log}
#systemctl enable mysqld
#systemctl start mysqld  &>>${log}
#mysql_secure_installation --set-root-pass ${mysql_root_password}  &>>${log}

- name: MySQL Setup
  hosts: all
  become: true
  tasks:
    - name: Configure Yum Repo for MySQL
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Disable default mysql version
      ansible.builtin.shell: yum module disable mysql -y

    - name: Install MySQL Community Server
      ansible.builtin.yum:
        name: mysql-community-server
        state: installed

    - name: Start MySQL Service
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
        enabled: yes

    - name: set root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1