#component=payment
#source common.sh
#rabbitmq_app_password=$1
#if [ -z "${rabbitmq_app_password}" ]; then
#echo Input RabbitMQ AppUser Password Missing
#exit 1
#fi
#func_python

- name: Payment Setup
  hosts: all
  become: true
  vars:
    component: payment
  tasks:
    - name: Python Setup
      ansible.builtin.import_tasks: python.yml