#log=/tmp/roboshop.log
#echo -e "\e[36m >>>>>>>>>>>>Configuring YUM Repos<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash &>>${log}
#echo -e "\e[36m >>>>>>>>>>>>Configure YUM Repos for RabbitMQ<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash &>>${log}
#echo -e "\e[36m >>>>>>>>>>>>Installing RabbitMQ Server<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#yum install rabbitmq-server -y &>>${log}
#echo -e "\e[36m >>>>>>>>>>>>Start RabbitMQ Service<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#systemctl enable rabbitmq-server
#systemctl start rabbitmq-server &>>${log}
#echo -e "\e[36m >>>>>>>>>>>>create one user for the application<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#rabbitmqctl add_user roboshop ${rabbitmq_app_password}
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>${log}

- name: RabbitMQ Setup
  hosts: all
  become: true
  tasks:
    - name: Install Erlang Repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Install RabbitMQ Repos
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Install RabbitMQ Server
      ansible.builtin.yum:
        name: rabbitmq-server
        state: installed

    - name: Restart RabbitMQ Service
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: restarted
        enabled: yes

    - name: Add Application User
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present