#-----------------------------------------------------------------------------------------------------1
#echo -e "\e[36m >>>>>>>>>>>>Installing Remirepo<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y &>>${log}
#-----------------------------------------------------------------------------------------------------1

#-----------------------------------------------------------------------------------------------------2
#echo -e "\e[36m >>>>>>>>>>>>Enabling redis module<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#yum module enable redis:remi-6.2 -y &>>${log}
#-----------------------------------------------------------------------------------------------------2

#-----------------------------------------------------------------------------------------------------3
#echo -e "\e[36m >>>>>>>>>>>>Installing redis<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#yum install redis -y &>>${log}
#-----------------------------------------------------------------------------------------------------3
-
#-----------------------------------------------------------------------------------------------------4
#echo -e "\e[36m >>>>>>>>>>>>Changing Listen Address<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#sed -i 's/127.0.0.1/0.0.0.0/' /etc/redis.conf /etc/redis/redis.conf &>>${log}
#-----------------------------------------------------------------------------------------------------4


#-----------------------------------------------------------------------------------------------------5
#echo -e "\e[36m >>>>>>>>>>>>Enabling and restart<<<<<<<<<<<<<<<< \e[0m"  | tee -a /tmp/roboshop.log
#systemctl enable redis
#systemctl restart redis
#

- name: Redis Setup
  hosts: all
  become: yes
  tasks:
    - name: Install Redis repo
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed
        disable_gpg_check: true

    - name: Enable redis module
      ansible.builtin.shell: yum module enable redis:remi-6.2 -y

    - name: Install Redis
      ansible.builtin.yum:
        name: redis
        state: installed

    - name: Update Listen address /etc/redis.conf
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Update listen address /etc/redis/redis.conf
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'


    - name: Restart Redis
      ansible.builtin.systemd:
        name: redis
        state: restarted
        enabled: yes