- name: User setup
  hosts: all
  become: yes
  vars:
    component: user
    schema: true
  tasks:
    - name: NodeJs setup
      ansible.builtin.import_tasks: nodejs.yml


#component=user
#source common.sh
#
#func_nodejs